- input: |
    5
    pizza
    atum
    coordenacao
    martelo
    costela
  output: |
    2 palavra(s) com letras dobradas:
    pizza
    coordenacao
    ---
    3 palavra(s) sem letras dobradas:
    atum
    martelo
    costela


- input: |
    3
    bicicleta
    aquario
    moda
  output: |
    0 palavra(s) com letras dobradas:
    ---
    3 palavra(s) sem letras dobradas:
    bicicleta
    aquario
    moda


- input: |
    3
    voo
    graal
    teen
  output: |
    3 palavra(s) com letras dobradas:
    voo
    graal
    teen
    ---
    0 palavra(s) sem letras dobradas:

